name: Update JSON

on:
  schedule:
    - cron: '0 */6 * * *'  # 每天运行一次

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 执行脚本更新 JSON 文件
        run: |
          python script.py

      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json
          git commit -m "Update index.json via scheduled task"
          git push
